name: JSFScan

on: [push]

jobs:
  JSFScan:
    runs-on: ubuntu-latest
    container:
      image: themaux/jsfscan:latest
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        CHAOS_KEY: ${{ secrets.CHAOS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Start scan
      run: /bin/bash ./recon.sh

      # IN W.I.P