name: JSFScan

on: [push]

jobs:
  JSFScan:

    runs-on: themaux/jsfscan:latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t themaux/jsfscan:local .


    - name: Start the scan
      run: docker run -e GITHUB_PASSWD="${{ secrets.GITHUB_TOKEN }}"
        -e USER_EMAIL="${{ secrets.USER_EMAIL }}"
        -e USER_PASSWORD="${{ secrets.USER_PASSWORD }}"
        -e CHAOS_KEY="${{ secrets.CHAOS_KEY }}"
        themaux/jsfscan:local

